
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL'; 
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL'; 
export const SHOW_FORGOT_EMAIL_MODAL = 'SHOW_FORGOT_EMAIL_MODAL'; 
export const SHOW_VIRIFY_EMAIL_MODAL = 'SHOW_VIRIFY_EMAIL_MODAL'; 

export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL'; 
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL'; 
export const HIDE_FORGOT_EMAIL_MODAL = 'HIDE_FORGOT_EMAIL_MODAL'; 
export const HIDE_VIRIFY_EMAIL_MODAL = 'HIDE_VIRIFY_EMAIL_MODAL'; 


// AUTH 
export const REGISTER = "REGISTER";
export const LOGIN    = "LOGIN";

